CREATE DATABASE [AshleyPelegMidterm]
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AshleyPelegMidterm] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AshleyPelegMidterm].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AshleyPelegMidterm] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET ARITHABORT OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AshleyPelegMidterm] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AshleyPelegMidterm] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AshleyPelegMidterm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AshleyPelegMidterm] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET RECOVERY FULL 
GO
ALTER DATABASE [AshleyPelegMidterm] SET  MULTI_USER 
GO
ALTER DATABASE [AshleyPelegMidterm] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AshleyPelegMidterm] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AshleyPelegMidterm] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AshleyPelegMidterm] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AshleyPelegMidterm] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AshleyPelegMidterm] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AshleyPelegMidterm', N'ON'
GO
ALTER DATABASE [AshleyPelegMidterm] SET QUERY_STORE = ON
GO
ALTER DATABASE [AshleyPelegMidterm] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AshleyPelegMidterm]
GO
/****** Object:  UserDefinedFunction [dbo].[ToTitleCase]    Script Date: 5/9/2025 6:04:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   FUNCTION [dbo].[ToTitleCase](@Input NVARCHAR(255))
RETURNS NVARCHAR(255)
AS
BEGIN
    DECLARE @Result NVARCHAR(255) = '';
    DECLARE @i INT = 1;
    DECLARE @CurrentChar CHAR(1);
    DECLARE @PrevChar CHAR(1) = ' ';

    WHILE @i <= LEN(@Input)
    BEGIN
        SET @CurrentChar = SUBSTRING(@Input, @i, 1);

        IF @PrevChar = ' '
            SET @Result = @Result + UPPER(@CurrentChar);
        ELSE
            SET @Result = @Result + LOWER(@CurrentChar);

        SET @PrevChar = @CurrentChar;
        SET @i = @i + 1;
    END

    RETURN @Result;
END;
GO
/****** Object:  Table [dbo].[Contact]    Script Date: 5/9/2025 6:04:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER DATABASE [AshleyPelegMidterm] SET  READ_WRITE 
GO
